"""Tests for G-code Slicer & FDM 3D-Printability Slicing Engine."""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path
import pytest

from badge3d_coin_generator import (
    CoinGenerator,
    FilamentType,
    InfillPattern,
    MeshData,
    OverhangAnalysis,
    SliceResult,
    SlicingConfig,
    analyze_mesh_overhangs,
    slice_coin,
    slice_mesh,
)
from badge3d_coin_generator.cli import main as cli_main
from badge3d_coin_generator.mcp_server import MCPServer
from badge3d_coin_generator.ui_server import create_ui_server
import threading
import time


def test_filament_properties():
    """Verify density and default extrusion temperatures across filament types."""
    assert FilamentType.PLA.density_g_cm3 == 1.24
    assert FilamentType.PETG.density_g_cm3 == 1.27
    assert FilamentType.ABS.density_g_cm3 == 1.04
    assert FilamentType.RESIN.density_g_cm3 == 1.15

    assert FilamentType.PLA.default_bed_temp == 60
    assert FilamentType.PETG.default_bed_temp == 75
    assert FilamentType.ABS.default_bed_temp == 100

    assert FilamentType.PLA.default_nozzle_temp == 205
    assert FilamentType.PETG.default_nozzle_temp == 235


def test_overhang_analysis():
    """Verify detection of overhang angles and support recommendations."""
    gen = CoinGenerator(radius=20.0, thickness=3.0, serrations=30, resolution=32)
    mesh = gen.generate()

    overhang = analyze_mesh_overhangs(mesh, threshold_degrees=45.0)
    assert isinstance(overhang, OverhangAnalysis)
    assert overhang.total_faces == mesh.triangle_count
    assert overhang.overhang_area_mm2 >= 0.0
    assert 0.0 <= overhang.overhang_percentage <= 100.0
    assert len(overhang.recommendations) > 0


def test_mesh_slicing_layer_count():
    """Verify horizontal layer plane intersection calculations."""
    gen = CoinGenerator(radius=15.0, thickness=2.0, serrations=20, resolution=24)
    mesh = gen.generate()

    cfg = SlicingConfig(layer_height=0.20, first_layer_height=0.25)
    result = slice_mesh(mesh, config=cfg)

    assert isinstance(result, SliceResult)
    assert result.total_layers > 5
    assert len(result.layers) == result.total_layers
    assert result.total_print_time_sec > 0.0
    assert result.total_filament_mm > 0.0
    assert result.total_filament_grams > 0.0

    # Ensure strictly increasing Z heights
    zs = [l.z_height for l in result.layers]
    assert all(zs[i] < zs[i + 1] for i in range(len(zs) - 1))

    # Check serialization
    d = result.to_dict()
    assert "total_layers" in d
    assert "total_filament_grams" in d
    assert "overhang" in d


def test_infill_patterns():
    """Verify rectilinear, grid, concentric, and triangles infill generation."""
    gen = CoinGenerator(radius=15.0, thickness=2.0, resolution=24)
    mesh = gen.generate()

    for pat in [InfillPattern.RECTILINEAR, InfillPattern.GRID, InfillPattern.CONCENTRIC, InfillPattern.TRIANGLES]:
        cfg = SlicingConfig(
            layer_height=0.25,
            infill_density=0.20,
            infill_pattern=pat,
        )
        res = slice_mesh(mesh, config=cfg)
        # Check that middle layers have infill segments
        mid_layer = res.layers[len(res.layers) // 2]
        assert len(mid_layer.infill_segments) > 0, f"Pattern {pat} generated no infill segments"


def test_gcode_synthesis_structure():
    """Verify generated G-code text format adheres to Marlin/RepRap conventions."""
    gen = CoinGenerator(radius=12.0, thickness=2.0, resolution=16)
    mesh = gen.generate()
    cfg = SlicingConfig(layer_height=0.30, filament_type=FilamentType.PLA)
    result = slice_mesh(mesh, config=cfg)
    gcode = result.to_gcode()

    assert "; Generated by Badge3D Coin Slicer" in gcode
    assert "G28 ; home all axes" in gcode
    assert f"M104 S{cfg.nozzle_temp}" in gcode
    assert f"M140 S{cfg.bed_temp}" in gcode
    assert "; --- LAYER 0" in gcode
    assert "M84 ; disable stepper motors" in gcode


def test_slice_coin_convenience_function():
    """Verify slice_coin works with dict, CoinGenerator, and MeshData."""
    # 1. From dict
    res1 = slice_coin({"radius": 15.0, "thickness": 2.0, "resolution": 16})
    assert res1.total_layers > 0

    # 2. From CoinGenerator
    gen = CoinGenerator(radius=15.0, thickness=2.0, resolution=16)
    res2 = slice_coin(gen)
    assert res2.total_layers > 0

    # 3. From MeshData
    mesh = gen.generate()
    res3 = slice_coin(mesh)
    assert res3.total_layers > 0


def test_mcp_coin_slice_gcode_tool():
    """Verify MCP tool call for coin_slice_gcode."""
    server = MCPServer()
    req = {
        "jsonrpc": "2.0",
        "id": 42,
        "method": "tools/call",
        "params": {
            "name": "coin_slice_gcode",
            "arguments": {
                "radius": 15.0,
                "thickness": 2.0,
                "layer_height": 0.30,
                "format": "json",
            },
        },
    }
    resp = server.handle_request(req)
    assert resp is not None
    assert "result" in resp
    assert not resp["result"].get("isError")

    text = resp["result"]["content"][0]["text"]
    data = json.loads(text)
    assert "total_layers" in data
    assert data["total_layers"] > 0

    # Summary markdown call
    req_summary = {
        "jsonrpc": "2.0",
        "id": 43,
        "method": "tools/call",
        "params": {
            "name": "coin_slice_gcode",
            "arguments": {
                "radius": 15.0,
                "thickness": 2.0,
                "format": "summary",
            },
        },
    }
    resp_sum = server.handle_request(req_summary)
    assert "G-Code Telemetry" in resp_sum["result"]["content"][0]["text"]


def test_ui_api_slice_gcode_endpoints():
    """Verify GET and POST /api/slice-gcode on ephemeral server."""
    server = create_ui_server(host="127.0.0.1", port=0)
    port = server.server_address[1]
    base_url = f"http://127.0.0.1:{port}"

    th = threading.Thread(target=server.serve_forever, daemon=True)
    th.start()
    time.sleep(0.05)

    try:
        # 1. GET /api/slice-gcode
        get_url = f"{base_url}/api/slice-gcode?radius=15.0&thickness=2.0&layer_height=0.30"
        with urllib.request.urlopen(get_url) as resp:
            assert resp.status == 200
            data = json.loads(resp.read().decode("utf-8"))
            assert "total_layers" in data

        # 2. POST /api/slice-gcode (JSON summary)
        post_url = f"{base_url}/api/slice-gcode"
        body = json.dumps({"radius": 15.0, "thickness": 2.0, "layer_height": 0.30}).encode("utf-8")
        req = urllib.request.Request(post_url, data=body, headers={"Content-Type": "application/json"})
        with urllib.request.urlopen(req) as resp:
            assert resp.status == 200
            data = json.loads(resp.read().decode("utf-8"))
            assert "total_layers" in data

        # 3. POST /api/slice-gcode (G-code file download)
        body_gcode = json.dumps({"radius": 15.0, "thickness": 2.0, "layer_height": 0.30, "format": "gcode"}).encode("utf-8")
        req_gcode = urllib.request.Request(post_url, data=body_gcode, headers={"Content-Type": "application/json"})
        with urllib.request.urlopen(req_gcode) as resp:
            assert resp.status == 200
            gcode_content = resp.read().decode("utf-8")
            assert "Generated by Badge3D Coin Slicer" in gcode_content
    finally:
        server.shutdown()
        server.server_close()
        th.join(timeout=1.0)


def test_cli_slice_subcommand(tmp_path: Path, capsys):
    """Verify CLI slice subcommand execution."""
    out_file = tmp_path / "test_coin.gcode"
    # CLI execution
    code = cli_main(["slice", "-r", "15.0", "-t", "2.0", "--layer-height", "0.30", "-o", str(out_file), "--json"])
    assert code == 0
    assert out_file.exists()
    assert out_file.stat().st_size > 100

    captured = capsys.readouterr()
    data = json.loads(captured.out)
    assert "total_layers" in data
